### ISSUE TITLE
Maximum number of pages in dropdown on mobile

### ISSUE THREAD

**Issue by thomcsmits** [dwh-outsite/dwhdelft.nl#549] opened 2024-03-05 21:40 UTC
When adding more items to the dropdown menu, the bottom items disappear in small window size

Desired outcome: scrollable dropdown menu in small window size

**Comment by laurensWe** [comment] 2024-03-07 09:08
from an UI perspective I would hate to have a scrollbar there as people mostly will not see this

**Comment by casperboone** [comment] 2024-03-07 12:40
I think the issue is mostly that the bottom of the navigation is cut off on non-home pages due to the `overflow:hidden` of the header. 

e.g.:
<img width="521" alt="image" src="https://github.com/dwh-outsite/dwhdelft.nl/assets/15815208/aa1218ed-f657-46e7-9cd3-0a2447f6d99e">

There's no trivial fix for this, sadly, requires some rethinking how the navigation and header work.

**Closed** 2024-11-10 20:08 UTC
Labels: bug
